finish-project03
MARS-JSU/Internship1400-backEnd-AlirezaMohammadi pull request #17
Opened 2021-08-16 13:29 UTC by mhmdialireza

2021-08-23 13:58 UTC, RAAvenger requested changes
<div dir=rtl>
سلام

خسته نباشی

کدت هنوز یکم با سالید شدن فاصله داره.

2021-08-23 13:58 UTC, RAAvenger commented on project03/App/Analyzing/Analyzor.php
> +
<div dir=rtl>
چرا این متغییر رو به عنوان متغییر کلاس تعریف میکنی؟ چرا Scope این متغییر همین متد نیست؟

2021-08-23 13:58 UTC, RAAvenger commented on project03/App/Analyzing/RebuildString.php
> +class RebuildString
<div dir=rtl>
چرا این کلاس رو از انالایزر استخراج کردی؟

2021-08-23 13:58 UTC, RAAvenger commented on project03/App/Contracts/MathOperationInterface.php
> +    public function answerForValue(CusotmTypeInterface $polyOrMono, float $value) :float;
<div dir=rtl>
جای polyOrMono یک اسم عمومیتر بذار.

2021-08-23 13:58 UTC, RAAvenger commented on project03/App/Operation/Operation.php
> +{
<div dir=rtl>
جای این کلاس برو همون PolyOperation و MonoOperation رو جوری بنویس که از MathOperationInterface تبعیت کنن. این کاری که اینجا کردی سالید نیست.

2021-08-23 15:01 UTC, mhmdialireza commented on project03/App/Analyzing/RebuildString.php
> +class RebuildString
کلاس آنالایزینگ فقط رو یه استرینگی میتونه کار کنه که قبلاش کلاس ریبیلد استرینگ تغییرش داده
کارشون هم با هم متفاوته
ریبیلداسترینگ تغییر میده استرینگو که نقاط مرزی از بین برن
و کلاس آنالایزینگ رشته رو میشکنه تا تک جمله ای هاشو پیدا کنه

2021-08-23 15:01 UTC, mhmdialireza commented on project03/App/Contracts/MathOperationInterface.php
> +    public function answerForValue(CusotmTypeInterface $polyOrMono, float $value) :float;
اصلاح شد

2021-08-23 15:03 UTC, mhmdialireza commented on project03/App/Operation/Operation.php
> +{
PolyOperation متد جمع و تفریق رو نداره ، نمیدونم دقیقا چطوری باید براشون اینترفیس بزارم
ولی روش فکر میکنم

2021-08-23 15:03 UTC, mhmdialireza commented on project03/App/Analyzing/Analyzor.php
> +
اصلاح شد

2021-08-30 17:21 UTC, hamedgk commented on project03/App/Operation/MonoOperation.php
> +        return $mono->getCoefficient() * ($value ** $mono->getPower());
بنظرت CustomTypeInterface یخورده کلی نیست؟
نظر من اینه که برای مونو و پلی هرکدوم یه اینترفیس بسازی که ویژگی های اصلی اونارو پیاده سازی کنه و توی کلاس های عملیاتی اینترفیس های مخصوص خودشونو بگیری .

2021-08-31 13:49 UTC, mhmdialireza commented on project03/App/Operation/MonoOperation.php
> +        return $mono->getCoefficient() * ($value ** $mono->getPower());
برای پلی و مونو دوتا اینترفیس ساختم که میتونی توی pr جدید ببینی
ولی برای عملیات ریاضی چون دقیقا متدها یکسانه
بنظرم یه اینترفیس کافیه
که باعث میشه اینجا اینترفیس رو پاس بدم

2021-08-31 13:54 UTC, hamedgk approved these changes

2021-09-01 06:58 UTC, farhadalghasi approved these changes

2021-09-06 17:18 UTC, RAAvenger approved these changes
سلام

خسته نباشی

کدت خوبه، یکی دوتا اصلاح کوچیک به چشمم اومد که بهتره انجامسون بدی.

2021-09-06 17:18 UTC, RAAvenger commented on project03/App/Types/Poly.php
> +            }
<div dir="rtl">
این دوتا foreach رو به for تغییر بده که بتونی شمارنده رو مدیریت کنی

2021-09-06 17:18 UTC, RAAvenger commented on project03/App/Types/Poly.php
> +            foreach ($this->monos as $index2 => &$mono2) {
<div dir="rtl">
از for  استفاده کن.

2021-09-08 22:15 UTC, merged