finish-project
MARS-JSU/Internship1400-backEnd-AlirezaMohammadi pull request #25
Opened 2021-09-05 10:24 UTC by mhmdialireza

2021-09-06 11:53 UTC, mhmdialireza commented
app\Contracts
app\Http\Controllers\V1
app\Services
app\Providers\ProjectServiceProviders.php
routes\api.php

2021-09-06 17:28 UTC, RAAvenger approved these changes
خسته نباشی. 

مرج کردی؟ تعدادی از فایلا انگار مرج شدن.

2021-09-06 17:28 UTC, RAAvenger commented on Laravel/app/Providers/ProjectServiceProvider.php
> +            return new AnalyzingService($app->make(Poly::class));
<div dir="rtl">
singleton بده و کلاس رو جوری تغییر بده که توی سازنده poly نگیره

2021-09-06 17:28 UTC, RAAvenger commented on Laravel/app/Services/PolyService.php
>      public function makePolyByRequestMonos(Request $request, string $monosName = 'monos') :Poly
<div dir="rtl">
اینجا نباید ریکوئست داشته باشیم.

2021-09-06 17:28 UTC, RAAvenger commented on Laravel/app/Providers/ProjectServiceProvider.php
> +            return new PolyService($app->make(Poly::class));
<div dir="rtl">
توی سازنده مقدار نده.

2021-09-06 17:38 UTC, RAAvenger requested changes

2021-09-06 17:38 UTC, RAAvenger commented on Laravel/app/Http/Controllers/V1/ApiResponseController.php
> +        $poly2 = $this->polyService->makePolyByRequestMonos($request,'monos2');
<div dir="rtl">
 به این متد به جای دادن request رشته یا json بده

2021-09-06 17:38 UTC, RAAvenger commented on Laravel/app/Http/Controllers/V1/ApiResponseController.php
> +        $arrayMonos = $this->polyService->getArrayMonos($sum);
<div dir="rtl">
چرا از poly->getMonos استفاده نمیکنی؟

2021-09-08 08:52 UTC, mhmdialireza commented on Laravel/app/Http/Controllers/V1/ApiResponseController.php
> +        $arrayMonos = $this->polyService->getArrayMonos($sum);
getMonos آرایه ای از مونو ها میده
ولی متدی که نوشتم یک آرایه‌ی دو بعدی از ضرایب و توانهاست

2021-09-13 15:16 UTC, merged