finish-project02
MARS-JSU/Internship1400-backEnd-AlirezaMohammadi pull request #9
Opened 2021-08-06 14:30 UTC by mhmdialireza

2021-08-06 17:44 UTC, RAAvenger requested changes

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +        $this->setDerivativePower($this->getPower() - 1);
<div dir=rtl>
همیشه به مقدار مشتق نیاز داریم که همیشه حسابش میکنی؟

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +            echo '+';
<div dir=rtl>
چرا از echo استفاده کردی؟

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +    public function printDerivativePhrase() {
<div dir=rtl>
پیشنهاد میکنم یک تابع برای مشتق داشته باشی که خروجیش یک mono باشه.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +    public function printPhrase() {
<div dir=rtl>
کلاس‌ها در اکثر زبان‌های برنامه نویسی یک متود به نام toString() دارن که پیشنهاد میکنم برای نمایش متنی کلاس همون متود رو رونویسی کنی( رفتار خیلی مرسومیه )

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +        return $this->coefficient * $n ** $this->power;
<div dir=rtl>
برای خوانایی بیشتر پرانتزگذاری کن.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +    private $sent;
<div dir=rtl>
برای خوانایی بیشتر نوع اینها رو مشخص کن.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +    public function sum(Mono $a) {
<div dir=rtl>
بهتره در سطح همین کلاس( بعنی داخل همین تابع ) بررسی کنی که اگر توان‌ها برابر نیستن اینجا Exception بدی.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +        $coefficient = floatval($this->coefficient) - floatval($a->coefficient);
<div dir=rtl>
اینجا هم مثل متود بالایی قبل از انجام عملیات به validation نیاز هست.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +        $coefficient = floatval($a->getCoefficient()) * floatval($this->getCoefficient());
<div dir=rtl>
این تابع floatval که به وفور استفاده شده نتیجه همون عدم تخصیص نوع به متغییر هست. :)

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Mono.php
> +    private $sent;
<div dir=rtl>
کاربرت صفت sent چیه؟

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Processing.php
> +    public function initialize() {
<div dir=rtl>
منظور از راه‌اندازی چیه؟ نمیشه اسم مناسبتری برای این تابع انتخاب کرد؟

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Processing.php
> +        return $this->getString();
<div dir=rtl>
همه عملیات‌های بالا روی صفت کلاس انجام شدن؟

یعنی اگر کاربر قبل از صدا زدن این تابع getString  رو صدا بزنه مقدار خروجی با وقتی که این تابع رو صدا زده متفاوته؟ به نظرت این اتفاق( خروجی یک تابع دوتا چیز متفاوت میتونه باشه ) درسته؟

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Processing.php
> +    public function initialize() {
<div dir=rtl>
همچنین با توجه به کارکرد این کلاس که تحلیل( Analysing ) و در نهایت استخراج یک چند جمله‌ای از متن هست انتظار میره که خروجی تابع اصلی یک چندجمله‌ای باشه.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Poly.php
> +    public function printDerivativePhrase() {
<div dir=rtl>
همون  toString  رو رونویس( override ) کنی بهتره.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Poly.php
> +    }
<div dir=rtl>
یکم بیشتر روی این توابع فکر کن( با بقیه هم همفکری کن ) اگه نتونستی بهترشون کنی بیا با هم حرف بزنیم.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Poly.php
> +    }
<div dir=rtl>
اصلی ترین داده‌ی کلاس رو از بیرون میشه راحت تغییر داد؟

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Poly.php
> +    }
<div dir=rtl>
اینم مثل همون poly هست. باید تغییرش از بیرون در حین پردازش محدود بشه.

2021-08-06 17:44 UTC, RAAvenger commented on project02/App/Poly.php
> +    private float $solve;
<div dir=rtl>
توی نامگذاری دقت کن. مثلا solve به معنی « حل کردن مسئله/مشکل » هست و اینجا شاید معنی درستی نده. دقت کن که متغییر قراره چه چیزی رو نگهداری کنه و با توجه به این براش نام انتخاب کن( از انتخاب نام‌های یکم مفصل هم نترس ).

2021-08-06 17:46 UTC, RAAvenger commented
<div dir=rtl>
سلام خسته نباشی.

کد خوبی نوشتی ولی یکم توی نامگذاری و تقسیم کار بین کلاس‌ها بیشتر کار کن.

2021-08-08 11:18 UTC, mhmdialireza commented on project02/App/Mono.php
> +        $this->setDerivativePower($this->getPower() - 1);
اصلاح شد

2021-08-08 11:19 UTC, mhmdialireza commented on project02/App/Mono.php
> +            echo '+';
اصلاح شد ، بجای echo خود رشته return می‌شه الان

2021-08-08 11:19 UTC, mhmdialireza commented on project02/App/Mono.php
> +    public function printDerivativePhrase() {
اصلاح شد

2021-08-08 11:19 UTC, mhmdialireza commented on project02/App/Mono.php
> +    public function printPhrase() {
اصلاح شد

2021-08-08 11:20 UTC, mhmdialireza commented on project02/App/Mono.php
> +        return $this->coefficient * $n ** $this->power;
اصلاح شد

2021-08-08 11:20 UTC, mhmdialireza commented on project02/App/Poly.php
> +    public function printDerivativePhrase() {
اصلاح شد

2021-08-08 11:20 UTC, mhmdialireza commented on project02/App/Poly.php
> +    }
متاسفانه راه حل بهتری به ذهنم نرسید

2021-08-08 11:21 UTC, mhmdialireza commented on project02/App/Poly.php
> +    }
خود این متد ستره ، دقیقا باید چه کاری انجام می‌دادم؟

2021-08-08 11:22 UTC, mhmdialireza commented on project02/App/Poly.php
> +    private float $solve;
اصلاح شد

2021-08-08 11:23 UTC, mhmdialireza commented on project02/App/Mono.php
> +    private $sent;
وقتی میخوام جمع و تفریق انجام بدم باید بدونم کدوم تک جمله ای ها فرستاده شدن

2021-08-08 11:24 UTC, mhmdialireza commented on project02/App/Mono.php
> +    public function sum(Mono $a) {
متدی که اطلاعات رو به این متد میفرسته چک میکنه ، غیر ممکنه توان‌ها یکی نباشن

2021-08-08 11:24 UTC, mhmdialireza commented on project02/App/Mono.php
> +        $coefficient = floatval($a->getCoefficient()) * floatval($this->getCoefficient());
اصلاح شد

2021-08-08 11:25 UTC, mhmdialireza commented on project02/App/Processing.php
> +    public function initialize() {
اصلاح شد

2021-08-08 11:25 UTC, mhmdialireza commented on project02/App/Processing.php
> +        return $this->getString();
متوجه شدم ، مشکل رو حل می‌کنم

2021-08-09 16:44 UTC, RAAvenger commented on project02/App/Analysing.php
> +    }
<div dir=rtl>
به همه این setterها و getterها نیاز هست؟

2021-08-09 16:44 UTC, RAAvenger commented on project02/App/Analysing.php
> +
<div dir="rtl">
اینتر اضافی

2021-08-09 16:44 UTC, RAAvenger commented on project02/App/Mono.php
> +    private bool $sent;
<div dir="rtl">
استفاده این متغییر sent چیه؟

2021-08-09 16:44 UTC, RAAvenger commented on project02/App/Mono.php
> +    public function setCoefficient($coefficient) :void {
<div dir="rtl">
مشخص کردن خروجی void برای getter لازم نیست.

2021-08-09 16:44 UTC, RAAvenger commented on project02/App/Mono.php
> +        return $coefficient.'x^'.$power;
<div dir="rtl">
چرا خروجی اینا mono نیست؟

2021-08-09 16:44 UTC, RAAvenger commented on project02/App/Poly.php
> +    private float $solve;
<div dir="rtl">
هنوز هم اون solve گنگه، یا براش کامنت بذار و یا تغییرش بده به یک چیز بهتر.

2021-08-10 17:50 UTC, RAAvenger approved these changes

2021-08-10 18:28 UTC, merged